{{- if eq .Values.scope.namespace true -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "streams-console.name" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "streams-console.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "streams-console.selectorLabels" . | nindent 4 }}
{{- end }}