{{- if ne .Values.scope.namespace true -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "streams-console.labels" . | nindent 4 }}
  name: {{ include "streams-console.name" . }}-prometheus-cr-{{ .Values.user }}
rules:
  - apiGroups: [ '' ]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: [ get, list, watch ]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: [ get, list, watch ]
  - nonResourceURLs: [ /metrics ]
    verbs: [ get ]
{{- end }}