nameOverride: "kafka-sink"

secret:
  argocd:
    enabled: true
    syncwave: "-2"

kafkasink:
 - name: moderated-reviews-sink
   topic: reviews.moderated
   partitions: 1
   contentMode: binary
 - name: reviews-sentiment-sink
   topic: reviews.sentiment
   partitions: 1
   contentMode: binary
  
kafka:
  bootstrapServer: 
  clientId: ""
  clientSecret: ""
  securityProtocol: ""
  saslMechanism: ""
  secret: kafka-secret

argocd:
  enabled: true
  syncwave: "-1"